export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const CHANGE_PW_SUCCESS = 'CHANGE_PW_SUCCESS';
export const CHANGE_PW_FAIL = 'CHANGE_PW_FAIL';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const GET_ALBUMS_SUCCESS = 'GET_ALBUMS_SUCCESS';
export const GET_ALBUMS_FAIL = 'GET_ALBUMS_FAIL';
export const GET_ALBUM_SUCCESS = 'GET_ALBUM_SUCCESS';
export const GET_ALBUM_FAIL = 'GET_ALBUM_FAIL';
export const ALBUM_AUTH_SUCCESS = 'ALBUM_AUTH_SUCCESS';
export const ALBUM_AUTH_FAIL = 'ALBUM_AUTH_FAIL';
export const ADD_ALBUM_SUCCESS = 'ADD_ALBUM_SUCCESS';
export const ADD_ALBUM_FAIL = 'ADD_ALBUM_FAIL';
export const DELETE_ALBUM_SUCCESS = 'DELETE_ALBUM_SUCCESS';
export const DELETE_ALBUM_FAIL = 'DELETE_ALBUM_FAIL';
export const CHANGE_ALBUM_NAME_SUCCESS = 'CHANGE_ALBUM_NAME_SUCCESS';
export const CHANGE_ALBUM_NAME_FAIL = 'CHANGE_ALBUM_NAME_FAIL';
export const CHANGE_ALBUM_PW_SUCCESS = 'CHANGE_ALBUM_PW_SUCCESS';
export const CHANGE_ALBUM_PW_FAIL = 'CHANGE_ALBUM_PW_FAIL';

export const GET_PICTURES_SUCCESS = 'GET_PICTURES_SUCCESS';
export const GET_PICTURES_FAIL = 'GET_PICTURES_FAIL';
export const VIEW_PICTURE_SUCCESS = 'VIEW_PICTURE_SUCCESS';
export const VIEW_PICTURE_FAIL = 'VIEW_PICTURE_FAIL';
export const ADD_PICTURE_SUCCESS = 'ADD_PICTURE_SUCCESS';
export const ADD_PICTURE_FAIL = 'ADD_PICTURE_FAIL';
export const DELETE_PICTURE_SUCCESS = 'DELETE_PICTURE_SUCCESS';
export const DELETE_PICTURE_FAIL = 'DELETE_PICTURE_FAIL';

export const GET_PROMPTS_SUCCESS = 'GET_PROMPTS_SUCCESS';
export const GET_PROMPTS_FAIL = 'GET_PROMPTS_FAIL';
export const VIEW_PROMPT_SUCCESS = 'VIEW_PROMPT_SUCCESS';
export const VIEW_PROMPT_FAIL = 'VIEW_PROMPT_FAIL';
export const ADD_PROMPT_SUCCESS = 'ADD_PROMPT_SUCCESS';
export const ADD_PROMPT_FAIL = 'ADD_PROMPT_FAIL';
export const DELETE_PROMPT_SUCCESS = 'DELETE_PROMPT_SUCCESS';
export const DELETE_PROMPT_FAIL = 'DELETE_PROMPT_FAIL';
